  =lpro= uses external scripts to build and install the projects it
  manages. This provides the flexibility needed to build a wide
  variety of projects that use different build systems, and to make it
  easier to add new ones without recompilation. Each script requires
  one command line argument: the directory in which the
  tool is to be run in. Each subdirectory of a script-type directory
  holds the scripts needed for a different tool.
* Build and Install Scripts
  In the =build-types=
** Build Scripts
  + Make
    #+BEGIN_SRC shell
    #!/bin/sh
    make -c $1
    #+END_SRC
  + Ninja
    #+BEGIN_SRC shell
    #!/bin/sh
    cd $1
    ninja
    #+END_SRC
** Install scripts
   Installation may or may not be ran as root, so no sudo.
   + Make
     #+BEGIN_SRC shell
     #!/bin/sh
     make -C $1 install
     #+END_SRC
* Version control scripts
  Version control scripts expect one argument: the base of the project
  to pull/update/ect. If a separate branch needs to be pulled, either
  create a custom build type or set the default remote pull branch.
* Initialization Scripts
   Initialization scripts are not supported by =lpro=, but may be in
   the future if enough people want it. Problems to tackle include
   passing arguments to the configure command and setting environment
   variables in a tool-agnostic way. Scripts may not be able to do
   this, and a solution in Lisp may be needed.
